name: Build
on: [push]
jobs:
  linux-build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/${{ github.repository_owner }}/builder
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.github_token }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Detect Conan Profile
        run: conan profile detect
      - name: Build conan package
        run: conan create -o test=True --build missing .
  static-analyze:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/${{ github.repository_owner }}/builder
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.github_token }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Create build directory
        run: mkdir -p build
      - name: Configure
        run: cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=ON ..
        working-directory: ./build
      - name: Run Clang-tidy
        run: run-clang-tidy -config-file=../.clang-tidy
        working-directory: ./build
