name: Build
on: [push]
jobs:
  linux-build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/${{ github.repository_owner }}/builder
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.github_token }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Create build directory
        run: mkdir -p build
      - name: Configure
        run: cmake -DCMAKE_INSTALL_PREFIX=/artifacts ..
        working-directory: ./build
      - name: Build
        run: cmake --build .
        working-directory: ./build
      - name: Run Unit Tests
        run: ctest --output-on-failure
        working-directory: ./build
      - name: Install
        working-directory: ./build
        run: cmake --build . -t install
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: sdk
          path: /artifacts
  static-analyze:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/${{ github.repository_owner }}/builder
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.github_token }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Create build directory
        run: mkdir -p build
      - name: Configure
        run: cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=ON ..
        working-directory: ./build
      - name: Run Clang-tidy
        run: run-clang-tidy -config-file=../.clang-tidy
        working-directory: ./build
