name: Build
on: [push]
jobs:
  linux-build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/${{ github.repository_owner }}/builder
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.github_token }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Create build directory
        run: mkdir -p build
      - name: Configure
        run: cmake ..
        working-directory: ./build
      - name: Build
        run: cmake --build .
        working-directory: ./build
      - name: Run Unit Tests
        run: ctest --output-on-failure
        working-directory: ./build
